<?php

namespace Tests\Unit;

use App\Utilities\Affiliates;
use Illuminate\Support\Facades\Storage;
use PHPUnit\Framework\TestCase;

class AffiliatesTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // Setup mock affiliates file
        Storage::fake('affiliates');
        Storage::disk('affiliates')->put(
            'affiliates.txt',
            file_get_contents(__DIR__ . './mocks/affiliates.txt')
        );
    }

    public function testGetError(): void
    {
        $affiliates = new Affiliates('affiliates.txt', 'affiliates');
        $this->assertNull($affiliates->getError());
    }
}
